### ISSUE TITLE
Error when running tests in spaceflights_pandas starter

### ISSUE THREAD

**Issue by michal-mmm** [kedro-org/kedro-starters#252]
## Description
When running `pytest` for the starter `spaceflights_pandas` the error occurs.

Exact place of the error:
https://github.com/kedro-org/kedro-starters/blob/9499a2c81cada09b4dbfea23552c4053f5a09aad/spaceflights-pandas/%7B%7B%20cookiecutter.repo_name%20%7D%7D/tests/test_run.py#L23

Code for the instantiated object:
https://github.com/kedro-org/kedro/blob/91468e64ea6f1fc4d51fe6313d738476189dd74a/kedro/framework/context/context.py#L148

## Context
I was trying to run tests.

## Steps to Reproduce
1. `kedro new --starter=spaceflights-pandas`
2. setting up venv (I did that using `uv`)
3. `pytest`

## Expected Result
Passing tests

## Actual Result
Tell us what happens instead.

```text
================================= short test summary info ==================================
ERROR tests/test_run.py::TestProjectContext::test_project_path - TypeError: KedroContext.__init__() missing 1 required positional argument: 'env'
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:
Relevant elements of `pyproject.toml`:
```toml
[project]
name = "spaceflights-pandas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "kedro-datasets[pandas-csvdataset,pandas-exceldataset,pandas-parquetdataset]==5.1.0",
    "kedro==0.19.9",
    "pandas>=2.2.3",
    "scikit-learn>=1.5.2",
]

[tool.kedro]
package_name = "spaceflights_pandas"
project_name = "Spaceflights Pandas"
kedro_init_version = "0.19.9"
tools = ['None']
example_pipeline = "False"
source_dir = "src"

[dependency-groups]
dev = [
    "kedro-viz>=10.0.0",
    "pytest>=8.3.3",
]

[tool.pytest.ini_options]
pythonpath = "src"
testpaths = "tests"
```

* Kedro version used (`pip show kedro` or `kedro -V`): 0.19.9
* Python version used (`python -V`): 3.10.15
* Operating system and version: macOS 15.1
